### ISSUE TITLE
"curl https://google.com" from linux1 terminal hangs

### ISSUE THREAD

**Issue by brunorijsman** [nre-learning/antidote#104]
I just tried NRE labs lesson "1. Your first API call"

The very first step ("curl https://google.com") just hangs (I waited for 2+ minutes)

After typing "Enter / Return" there is zero output, and I don't get my prompt back, ever.

The terminal is in that state right now (as of Wed 17-Oct-2018 9:20am Pacific time).

I will leave the window open for a few hours.

**Comment by Mierdin** [comment]
@brunorijsman Thanks for the feedback. Indeed, we explicitly deny access to internet resources from the containers, for security purposes. The idea is that all of the resources for the lesson should be built as part of the lesson, and therefore become self-sufficient.

I do agree that this should be clearer in the REST APIs lesson, and should have an explicit mention in the docs, so I'll keep this issue open for now in order to track those efforts.
