### ISSUE TITLE
Decouple lesson ID from lesson definition file

### ISSUE THREAD

**Issue by jnpr-raylam** [nre-learning/antidote#122]
Lesson ID should be decoupled from the syringe.yaml lesson definition file, so that lesson contributors don't have to take care the lesson ID.

for lessonID variable, can be parsed from fileList variable in def.ImportLessonDefs

for labguide / lessondiagram, can pass one more env vars in syringe pod (e.g., `SYRINGE_LESSON_REPO_RAW_URL` and configure it to `https://raw.githubusercontent.com/nre-learning/antidote/master`), and lessons just contain something like `{{ RAW_URL }}/stage1/guide.md` in the definition file, and syringe renders it dynamically by prepend with the env vars and `/lesson/lesson-<ID>`

for linux container to access lesson content, modify syringe pods and jobs scheduler to add `subPath` in container's volumeMounts (e.g. `subPath: lessons/lesson-<ID>`), so in the lab guide, we can run something like `cat /antidote/stage1/guide.md`

**Comment by Mierdin** [comment]
IMO this is too much complexity for something that's a fairly simple one-time thing. The lesson import process uses `filepath.Walk`, which parses files in lexical order, so we're looking at a change of existing lesson IDs, since I'm assuming the existing lessons would have their lesson IDs removed as well. In addition, the moment we rename a lesson, it's in a different order. Too many wrinkles to implement something that I perceive as a non-problem right now. Takes a few seconds to look at the existing lesson list and pick the next one - it's simple, and exactly predictable.

Wrt your last paragraph, talking about restricting the scope of the `/antidote` directory, that's definitely possible. I don't see a pressing reason to go that direction right now - other than making the path a bit longer, I like that we're not limiting what users can see - the lesson guide is just that - a guide. If things get unwieldy, we can definitely revisit this and consider how syringe maps the lesson directory into the lesson pods.

I'm going to close this, since I don't see a path forward, especially wrt the proposed elimination of lesson IDs.
