### ISSUE TITLE
Improve contribution guide in the docs

### ISSUE THREAD

**Issue by jameskellynet** [nre-learning/antidote#17]
There are some sloppy sections in this part of the docs to clean up, and we need to create a build how-to and a testing how-to for contributors.

**Comment by jameskellynet** [comment]
We also need to add a section about documentation contributions.

**Comment by Mierdin** [comment]
Also need a doc for reviewers. Not only syntax but the spirit of the project. Focusing on the workflow rather than just "automating the network". Being neat with diagrams and examples. Not only for reviewers but also so contributors know what to expect. Convey that our goal is to make this the first impression for automators, so it has to preserve that.

**Comment by Mierdin** [comment]
I believe this should be completed as of https://github.com/nre-learning/antidote/pull/108.
