### ISSUE TITLE
Allow rebuilding the docs using a Docker container

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote#45]
The instructions in building the docs rely on venv to install sphinx, AFAIU.

I'd prefer to be able to trigger a rebuild inside a Docker container, to avoid installing a copy of all the libs in a "volatile" directory on my main work env (and docker should be quite well known in the Antidote contributors ?).

The readthedocs project seems to be using such a Docker image internally, but there doesn't seem to be a script that allows sharing the checked out docs with the build container... or I didn't find it with a very quick search, at least.

Hope this looks interesting.

**Comment by Mierdin** [comment]
`virtualenv` is widely used by those familiar with readthedocs and sphinx, as it's the primary method of ensuring that dependencies are contained in a single place so you don't dirty the system install location.

The docker method is certainly possible, however. Assume you have a build script called "build.sh", that looks something like this:

```
#!/bin/bash

pip install -r /docs/requirements.txt
cd /docs && make html
```

You can then build the docs using the following - note the `-v` flag to map the present working directory to `/docs`:

```
 docker run -v $(pwd):/docs python /docs/build.sh
```

This works, but because a new container is created for each run, dependencies are installed fresh each time. Hope that helps.
